#############################################################################
# Makefile for building: augmentedReality
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue Jan 5 13:32:12 2016
# Project:  augmentedReality.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile augmentedReality.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DHAVE_CONFIG_H=1 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/vtk-5.8 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQVTK -lvtkCommon -lvtkIO -lvtkRendering -lvtkGraphics -lvtkFiltering -lvtkHybrid -lvtkVolumeRendering -ldcmdata -lofstd -loflog -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dcmCatalog.cpp \
		augreality.cpp \
		endoQuery.cpp \
		seriesdialog.cpp \
		vtkdicom.cpp moc_augreality.cpp \
		moc_seriesdialog.cpp
OBJECTS       = main.o \
		dcmCatalog.o \
		augreality.o \
		endoQuery.o \
		seriesdialog.o \
		vtkdicom.o \
		moc_augreality.o \
		moc_seriesdialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		augmentedReality.pro
QMAKE_TARGET  = augmentedReality
DESTDIR       = 
TARGET        = augmentedReality

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_augreality.h ui_seriesdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: augmentedReality.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile augmentedReality.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile augmentedReality.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/augmentedReality1.0.0 || $(MKDIR) .tmp/augmentedReality1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/augmentedReality1.0.0/ && $(COPY_FILE) --parents augreality.h dcmCatalog.h endoQuery.h seriesdialog.h vtkdicom.h .tmp/augmentedReality1.0.0/ && $(COPY_FILE) --parents main.cpp dcmCatalog.cpp augreality.cpp endoQuery.cpp seriesdialog.cpp vtkdicom.cpp .tmp/augmentedReality1.0.0/ && $(COPY_FILE) --parents augreality.ui seriesdialog.ui .tmp/augmentedReality1.0.0/ && (cd `dirname .tmp/augmentedReality1.0.0` && $(TAR) augmentedReality1.0.0.tar augmentedReality1.0.0 && $(COMPRESS) augmentedReality1.0.0.tar) && $(MOVE) `dirname .tmp/augmentedReality1.0.0`/augmentedReality1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/augmentedReality1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_augreality.cpp moc_seriesdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_augreality.cpp moc_seriesdialog.cpp
moc_augreality.cpp: dcmCatalog.h \
		endoQuery.h \
		vtkdicom.h \
		augreality.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) augreality.h -o moc_augreality.cpp

moc_seriesdialog.cpp: seriesdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) seriesdialog.h -o moc_seriesdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_augreality.h ui_seriesdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_augreality.h ui_seriesdialog.h
ui_augreality.h: augreality.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic augreality.ui -o ui_augreality.h

ui_seriesdialog.h: seriesdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic seriesdialog.ui -o ui_seriesdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp augreality.h \
		dcmCatalog.h \
		endoQuery.h \
		vtkdicom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dcmCatalog.o: dcmCatalog.cpp dcmCatalog.h \
		seriesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcmCatalog.o dcmCatalog.cpp

augreality.o: augreality.cpp augreality.h \
		dcmCatalog.h \
		endoQuery.h \
		vtkdicom.h \
		ui_augreality.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o augreality.o augreality.cpp

endoQuery.o: endoQuery.cpp endoQuery.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o endoQuery.o endoQuery.cpp

seriesdialog.o: seriesdialog.cpp seriesdialog.h \
		ui_seriesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seriesdialog.o seriesdialog.cpp

vtkdicom.o: vtkdicom.cpp vtkdicom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vtkdicom.o vtkdicom.cpp

moc_augreality.o: moc_augreality.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_augreality.o moc_augreality.cpp

moc_seriesdialog.o: moc_seriesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seriesdialog.o moc_seriesdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

